language: python
sudo: false
python: 3.6

env:
  global:
    - AWS_DEFAULT_REGION=us-east-1

before_deploy:
  - zip -r latest .
  - mkdir -p deploy_dest
  - cp latest.zip deploy_dest/$TRAVIS_COMMIT.zip
  - mv latest.zip deploy_dest/latest.zip

deploy:
  # push zips to s3
    provider:          s3
    access_key_id:     $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket:            $AWS_BUCKET
    region:            $AWS_BUCKET_REGION
    local_dir:         deploy_dest
    skip_cleanup:      true
    on:
      branch: master